import sanitizeHtml from "sanitize-html";
export const plainText = value => sanitizeHtml(String(value ?? ""), { allowedTags: [], allowedAttributes: {} }).replace(/&nbsp;/g, " ").replace(/&amp;/g, "&").trim();
const normalize = value => plainText(value).toLowerCase().replace(/[^a-z0-9+#.]+/g, " ").trim();
const contains = (haystack, term) => (` ${normalize(haystack)} `).includes(` ${normalize(term)} `);
const ratio = (matched, total) => total ? Math.round(matched / total * 100) : null;
export const analyzeATS = (resume, job, profile = {}) => {
  const sections = resume.sections;
  const visible = key => !sections || sections.some(s => s.type === key && !s.hidden && s.content === undefined);
  const text = [resume.jobTitle, visible("summary") ? resume.summary : "", ...(visible("experience") ? (resume.experience ?? []).flatMap(e => [e.title, e.companyName, e.workSummary]) : []), ...(visible("education") ? (resume.education ?? []).flatMap(e => [e.degree, e.major]) : []), ...(visible("skills") ? (resume.skills ?? []).map(s => s.name) : []), ...(sections ?? []).filter(s => !s.hidden).map(s => s.content ?? "")].map(plainText).join(" ");
  const keywords = [...new Set([...(job.analysis?.keywords ?? []), ...(job.analysis?.requiredSkills ?? [])].map(s => s.trim()).filter(Boolean))];
  const required = job.analysis?.requiredSkills ?? [];
  const matchedKeywords = keywords.filter(k => contains(text, k));
  const missingKeywords = keywords.filter(k => !contains(text, k));
  const matches = required.map(skill => ({ skill, status: contains(text, skill) ? "MATCHED" : (profile.skills ?? []).some(s => contains(s.name, skill)) ? "PARTIAL" : "MISSING" }));
  const bullets = (resume.experience ?? []).flatMap((e, index) => plainText(e.workSummary).split(/(?<=[.!?])\s+|\n/).filter(Boolean).map(text => ({ index, text })));
  const weakBullets = bullets.filter(b => b.text.split(/\s+/).length < 8 || /responsible for|worked on|helped with|hard.?working|team player/i.test(b.text));
  const measured = bullets.filter(b => /\d/.test(b.text)).length;
  const words = text.split(/\s+/).filter(Boolean).length;
  const keywordMatch = ratio(matchedKeywords.length, keywords.length);
  const skillsMatch = ratio(matches.filter(s => s.status === "MATCHED").length, required.length);
  const experienceText = (resume.experience ?? []).map(e => `${e.title} ${plainText(e.workSummary)}`).join(" ");
  const experienceRelevance = ratio(required.filter(k => contains(experienceText, k)).length, required.length);
  const achievementStrength = ratio(measured, bullets.length);
  const readability = words ? Math.max(0, 100 - weakBullets.length * 8 - (words > 1000 ? 20 : 0)) : 0;
  const weakSections = [!resume.summary && "Summary", !resume.experience?.length && "Experience", !resume.skills?.length && "Skills"].filter(Boolean);
  const formatting = Math.max(0, 100 - (resume.template === "modern" ? 15 : 0) - (!resume.email ? 20 : 0) - (words > 1200 ? 20 : 0));
  const repeatedKeywords = keywords.filter(k => normalize(text).split(normalize(k)).length - 1 > 8);
  const available = [keywordMatch, skillsMatch, experienceRelevance, achievementStrength, readability, formatting].filter(v => v !== null);
  return { overallScore: Math.round(available.reduce((a, b) => a + b, 0) / available.length), atsCompatibility: formatting, keywordMatch, experienceRelevance, skillsMatch, achievementStrength, readability, formatting, missingKeywords, matchedKeywords, matches, weakSections, weakBullets, repeatedKeywords, wordCount: words, recommendations: [ ...(missingKeywords.length ? ["Review missing terms. Add only skills or experience you actually possess."] : []), ...(weakBullets.length ? ["Clarify your action, scope and outcome in the highlighted bullets."] : []), ...(measured < bullets.length ? ["Where known, explain evidence of impact. Metrics are optional; never invent numbers."] : []), ...(words > 1000 ? ["Review length and relevance before exporting."] : []) ], explanations: { overallScore: "Unweighted mean of available diagnostic scores. This is a local heuristic, not an employer ATS score or hiring prediction.", keywordMatch: "Exact normalized phrase coverage of the job's extracted keywords and required skills.", skillsMatch: "Required skills explicitly mentioned in the visible resume. Profile-only skills are PARTIAL.", experienceRelevance: "Required skills explicitly mentioned in work history; this does not infer expertise or seniority.", achievementStrength: "Percentage of experience statements containing a number. Qualitative achievements can still be strong.", readability: "Starts at 100, subtracts 8 per short or generic statement, and 20 above 1,000 words.", formatting: "Starts at 100; subtracts 15 for the offset Modern layout, 20 for missing email, and 20 above 1,200 words.", missingData: "A null score means the source lacks evidence needed to calculate it. No ATS success is guaranteed." } };
};
